FROM httpd
MAINTAINER m510.net

RUN apt-get update -y && apt-get upgrade -y
#RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
#ENV LANG ja_JP.utf8

#RUN /usr/local/bin/gem install passenger --no-rdoc --no-ri
#RUN /usr/local/bin/passenger-install-apache2-module --auto --languages ruby

